#Anything that is optional which you are not using, just delete that line. You can also delete any of the '#comments'

modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory
license="MIT Liscense" #mandatory https://choosealicense.com/
issueTrackerURL="https://github.com/SecretJuice/the-rock-mod/issues" #optional

[[mods]] #mandatory
modId="sj_rock_mod" #mandatory
version="1.16.4-1.0.0.0" #mandatory
displayName="The Rock Mod" #mandatory
updateJSONURL="http://fillmein.me/" #optional
displayURL="https://github.com/SecretJuice/the-rock-mod" #optional

#logoFile="rock.png" #optional

credits="Thanks to mathidiot for the textures." #optional
authors="SecretJuice" #optional
description='''
A mod that adds rocks you can throw!

Hold LControl and Right-Click on obsidian or bedrock with different stones to get rocks.

Use rocks to throw them like snowballs!
''' #mandatory
